apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nginx
      name: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /data/nfs
          name: cephfs
        securityContext:
          privileged: false
      restartPolicy: Always
      volumes:
        - name: cephfs
          persistentVolumeClaim:
            claimName: cephfs-pvc